### ISSUE TITLE
Can't get absolute imports to work

### ISSUE THREAD

**Issue by koenbok** [koenbok/monobase#5]
It's so much better to have `import { MyComponent } from "components/MyComponent"` in a page.

But I can't get it to work in projects. These are my notes to self:

In theory, you just need to set `baseUrl` in `tsconfig.json` and it should work. VSCode indeed picks this up perfectly, but when you run the little server, it gives an error saying: `Cannot find module 'components/Template'`.

My best guess right now is that `ts-node` which uses `ts-loader` for these, does not resolve to the right path because:

1) It thinks it's in a different folder (maybe Monobase module) OR
2) The top level dynamic `require` in `page.render` somehow breaks the subsequent imports (although relative imports work fine).

I'm kind of stuck and it's late so good luck future self.

**Comment by koenbok** [comment]
Full stack trace:

```
Error: Cannot find module 'components/Template'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (<project>/pages/index.tsx:4:18)
    at Module._compile (module.js:660:30)
    at Module.m._compile (<monobase>/node_modules/ts-node/src/index.ts:610:21)
    at Module.m._compile (<monobase>/node_modules/ts-node/src/index.ts:610:21)
    at Module._extensions..js (module.js:671:10)
    at require.extensions.(anonymous function) (<monobase>/node_modules/ts-node/src/index.ts:616:1)
    at Object.require.extensions.(anonymous function) [as .tsx] (<monobase>/node_modules/ts-node/src/index.ts:616:1)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
```

**Comment by fverloop** [comment]
Maybe this helps. For Cloud, I only got this working by using a different (but almost identical) TS loader: https://github.com/s-panferov/awesome-typescript-loader

**Comment by koenbok** [comment]
Yes, but I needed `ts-node` too and generally have a more complex setup with the example project running from _within_ the actual project etc. This finally was the main fix: https://github.com/koenbok/monobase/blob/master/src/cli.ts#L55

https://www.npmjs.com/package/tsconfig-paths
